name: Options Data Collection

on:
  schedule:
    # 8:00 PM EST (0:00 UTC)
    - cron: '0 0 * * 1-5'
    # 9:20 AM EST (13:20 UTC)
    - cron: '20 13 * * 1-5'
  workflow_dispatch:  # Allow manual trigger

jobs:
  collect-options-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy yfinance
        
    - name: Create options_data directory
      run: mkdir -p options_data
      
    - name: Run Options Analysis Script
      run: python options_analysis.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add options_data/
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
        git commit -m "Options data update: $timestamp" || echo "No changes to commit"
        git push
