name: Options Data Collection

on:
  schedule:
    # Target: 8:00 PM EST (0:00 UTC) - Set 30 minutes earlier to account for delays
    - cron: '00 00 * * 2-6'  # 8:00 PM EST (00:00 GMT next day) - Note: shifts to Tue-Sat in GMT
    
    # Target: 9:20 AM EST (13:20 UTC)
    - cron: '01 13 * * 1-5'  # 9:01 AM EST → should finish ~9:28 AM EST
  
  workflow_dispatch:  # Allow manual trigger
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: boolean

jobs:
  collect-options-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'
        
    # Add the caching step here, between Python setup and dependency installation
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scipy yfinance pyarrow requests
        pip install -r requirements.txt
        
    - name: Create options_data directory
      run: mkdir -p options_data
      
    - name: Run Options Analysis Script
      env:
        DISCORD_TRADINGVIEW_WEBHOOK: ${{ secrets.DISCORD_TRADINGVIEW_WEBHOOK }}
        DISCORD_OVERNIGHT_WEBHOOK: ${{ secrets.DISCORD_OVERNIGHT_WEBHOOK }}
        DISCORD_DAILY_WEBHOOK: ${{ secrets.DISCORD_DAILY_WEBHOOK }}
      run: |
        if [[ "${{ github.event.inputs.test_mode }}" == "true" ]]; then
          echo "Running in TEST MODE"
          python -c "from main import run_automated_data_collection; run_automated_data_collection(test_mode=True)"
        else
          echo "Running in PRODUCTION MODE"
          python main.py
        fi
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add options_data*/ # This will add both options_data and options_data_test
        timestamp=$(date -u +"%Y-%m-%d %H:%M:%S")
        git commit -m "Options data update: $timestamp" || echo "No changes to commit"
        git push